### ISSUE TITLE
No transforms given or passed

### ISSUE THREAD

**Issue by tarrow** [ContentMine/norma#14]
ERROR org.xmlcml.norma.NormaTransformer  - no transforms given/parsed

is a common error to get even after the application runs successfully. It also appears a lot in ami's unit tests.

**Comment by petermr** [comment]
It should be removed and a lot of verbiage should also be removed.

**Comment by petermr** [comment]
I may have removed this - please check and close

**Comment by tarrow** [comment]
This generally seems to be fixed now (unless you don't pass it a transform or an xslt.
