### ISSUE TITLE
Document cmine

### ISSUE THREAD

**Issue by tarrow** [ContentMine/norma#19]
We need to document cmine so that people know how to use it. It is rather arcane.

**Comment by petermr** [comment]
It's also fairly new. There's a confusion between `cmine` functions and `ami` functions that I continue to try to tease out.
See `org.xmlcml.ami2.plugins.CommandProcessorTest` for some of the latest syntax.

**Comment by tarrow** [comment]
This probably shouldn't be in norma (since all the cmine command code is in ami) hence closing.
