### ISSUE TITLE
Replace Javax transformations (XSLT) with Saxon

### ISSUE THREAD

**Issue by petermr** [ContentMine/norma#25]
Javax uses Xerces/Xalan (usually) and is often difficult to wrap. It also doesn't do XSLT2.0. Worth trying to see if it can be replaced by the Open Source Saxon which is better, more advanced, does XSLT2.0 and a lot more and has a friendly Guru (Mike Kay).

**Comment by tarrow** [comment]
I believe that we already use Saxon in norma. I may be wrong though. So that you have somewhere to look up have a look at: /norma/src/main/java/org/xmlcml/norma/util/TransformerWrapper.java

**Comment by tarrow** [comment]
@petermr can you have a look at this and confirm if it is the case. If so could you close the ticket?
