### ISSUE TITLE
Cannot Use Java Home

### ISSUE THREAD

**Issue by tarrow** [ContentMine/norma#36]
This is a message from Andrew

> 
> My JAVA_HOME points to: /usr/java/jre1.8.0_66/bin/java
> but Norma fails with an error message saying that it cannot use the JAVA_HOME path /usr/java/jre1.8.0_66/bin/java/bin/java
> 
> I have tried combinations of trunaction of JAVA_HOME in the .bash_profile file to no avail?
> 
> Can you help please?

**Comment by simulsys** [comment]
Hi, as requested by Tom, here's a few background details. I am using Mint 17 Rosa Linux, and I installed from .deb files. I am using xterm to get to the terminal, and running from /home/[account name]/

Thanks for the help,

**Comment by petermr** [comment]
I am almost certain that you do NOT need the final `/bin/java`.

Try 
```
usr/java/jre1.8.0_66/
```

**Comment by simulsys** [comment]
I truncated JAVA_HOME as advised and the norma command ran with a warning about no Cterm being built?

I then ran 
$ cmine Documents/pollination 
and quite a lot happened. Unfortunately it emptied my target folder, so I shall try again. Many thanks for the advice.
Cheers.

**Comment by simulsys** [comment]
I ran the aardvark example, got 111 returns, but then received the following error message:
Error: EOENT, No such file or directory 'PMC4799876/eupmc_result.json'
and a pile of file location calls?
Can you help please?

**Comment by petermr** [comment]
@simulsys - 
```
Error: EOENT, No such file or directory 'PMC4799876/eupmc_result.json'
```
was a bug. install the next version:
```
npm install --global getpapers
```
and test 
```
getpapers --version
```
should give 0.4.5 or higher

The JAVA_HOME problem you should probably clean and start again. if your project is in `Document/pollination`,
```
cd Document
cmine pollination
```

**Comment by simulsys** [comment]
Many thanks. I reinstalled Mint as it was getting a bit scrambled, so I have a totally clean install. When I run the suggested code after installing getpapers I get the following:

andrew@andrew-Dimension-5000 ~ $ getpapers --version
/usr/bin/env: node: No such file or directory
andrew@andrew-Dimension-5000 ~ $ ls /usr/bin/en*
/usr/bin/enc2xs   /usr/bin/enchant-lsmod  /usr/bin/envsubst
/usr/bin/enchant  /usr/bin/env
andrew@andrew-Dimension-5000 ~ $

I can see the file is there? Any help gratefully received.

**Comment by tarrow** [comment]
It looks like you don't have a binary called node installed. It might be that you need to find a package called something like nodejs-legacy. Or you can put in a symlink with something like:
```sudo ln -s /usr/bin/nodejs /usr/bin/node```

**Comment by tarrow** [comment]
If this fails then please don't hesitate to open another bug report but to help us keep track of things I'm going to close this one since the initial issue (with Java home) sounds like it is fixed.
