### ISSUE TITLE
cmine does not work properly

### ISSUE THREAD

**Issue by simulsys** [ContentMine/norma#40]
Hi!

After successfully running getpapers I tried cmine test and cmine test2. On both occasions I had blank output. I then ran norma to no avail. Whe I run cmine test2 I get a verbose output ending with:

 WARN  org.xmlcml.ami2.plugins.ResultsAnalysis  - Null pluginOption
35355 [main] WARN  org.xmlcml.ami2.plugins.ResultsAnalysis  - Null pluginOption
35356 [main] WARN  org.xmlcml.ami2.plugins.ResultsAnalysis  - Null pluginOption
35356 [main] WARN  org.xmlcml.ami2.plugins.ResultsAnalysis  - Null pluginOption
35357 [main] WARN  org.xmlcml.ami2.plugins.ResultsAnalysis  - Null pluginOption

How do I get an e2e success please?

**Comment by petermr** [comment]
We need more information, including what is in your project directory `test`. My immediate reaction is that `test` may not have any `CTree`s in it. It's probably a good idea to create a small test with, say, 5 `CTree`s. 

I think we need to distribute a small regression test with `norma`.

**Comment by simulsys** [comment]
The directory test has 17k+ numbered files named: PMCnnnnn
It also has the following HTML files:
andrew@andrew-Dimension-5000 ~ $ ls -ls test/*html
4 -rw-r--r-- 1 andrew andrew 941 May 10 01:43 test/commonest.dataTables.html
4 -rw-r--r-- 1 andrew andrew 941 May 10 01:43 test/count.dataTables.html
4 -rw-r--r-- 1 andrew andrew 941 May 10 01:43 test/entries.dataTables.html
4 -rw-r--r-- 1 andrew andrew 941 May 10 01:43 test/full.dataTables.html

and the following XML files:
-rw-r--r-- 1 andrew andrew       72 May 10 01:41 sequence.dnaprimer.count.xml
-rw-r--r-- 1 andrew andrew       70 May 10 01:41 sequence.dnaprimer.documents.xml
-rw-r--r-- 1 andrew andrew       64 May 10 01:41 sequence.dnaprimer.snippets.xml
-rw-r--r-- 1 andrew andrew       72 May 10 01:43 species.binomial.count.xml
-rw-r--r-- 1 andrew andrew       70 May 10 01:43 species.binomial.documents.xml
-rw-r--r-- 1 andrew andrew       64 May 10 01:43 species.binomial.snippets.xml
-rw-r--r-- 1 andrew andrew       72 May 10 01:43 species.genus.count.xml
-rw-r--r-- 1 andrew andrew       70 May 10 01:43 species.genus.documents.xml
-rw-r--r-- 1 andrew andrew       64 May 10 01:42 species.genus.snippets.xml
-rw-r--r-- 1 andrew andrew       72 May 10 01:40 word.frequencies.count.xml
-rw-r--r-- 1 andrew andrew       70 May 10 01:40 word.frequencies.documents.xml
-rw-r--r-- 1 andrew andrew       64 May 10 01:40 word.frequencies.snippets.xml

I will have to investigate how to use CTrees.

Many thanks,

**Comment by tarrow** [comment]
Hi,

Looks like you had a successful run in general. You can see a simple table summary of the output in the html files. If you open full.dataTables.html in a browser you'll see what it looks like.

I'm excited that it worked on 17k papers at a time (I've never run it on anywhere near that many!). 

A CTree is the name we've given to those folders inside test (in your case) which contain a paper (in this case fulltext.xml) and optionally the paper converted to the format we can mine (scholarly.html), some metadata, and finally the mined results (you can see them for each invididual paper in test/PPMC123nnn/results/)

**Comment by petermr** [comment]
thanks @simulsys - great stuff.
@tarrow I think you mean 1.7K not 17K, but even so...
well done

**Comment by tarrow** [comment]
I did :) ; @simulsys can you let us know if you have any further problems in a new ticket. It looks like it is working as planned to me.
